%% %odor list
 odor_list = [{'water'}; ...    
    {'isoborneol'} ;...
    {'hexylacetate'} ;...
    {'40mM NaCl'} ;...
    {'benzaldehyde'} ;...
   {'1-pentanol'}; ...        %alcohol 
   {'4-hexen-3-one'}; ...        
   {'ethyl acetate'}; ...       
    {'2,5-dimethylpyrazine'}; ...        %alcohol 
%     {'isoamyl acetate'} ;...
%     {'trans-cinnamaldehyde'} ;...
    {'4,5-dimethylthiazole'}; ...
%     {'1-pentanol & 4-hexen-3-one'}; ...
%     {'2,5 dimethylpyrazine'}; ... 
%     {'2-ethylhexanoic acid'}; ...
%     {'2-ethylpyrazine'}; ...
%     {'2-pentanone'}; ...
%     {'2-pyrrolidinone'}; ...
%     {'3,3-dimethylacrylic acid'}; ...
%     {'3-methyl-2-buten-1-ol'}; ...
%     {'4-hexen-3-one'}; ...              %ketone
%     {'benzaldehyde'}; ...
%     {'benzoic acid'}; ...
%     {'benzylamine'}; ...
%     {'benzyl alcohol'}; ...
%     {'dimethoxymethane'}; ...
%     {'ethanolamine'}; ...
%     {'ethyl acetate'}; ...
%     {'ethyl benzoate'}; ...
%     {'furfuryl alcohol'}; ...
%     {'gamma-butyrolactone'}; ...
%     {'glycerol'}; ...
%     {'isobutyl alcohol'}; ...
%     {'L-aspartic acid'}; ...
%     {'methyl benzoate'}; ...
%    {'methyl propionate'}; ...
%     {'nerol'}; ...
%      {'acetylsalicylic acid'}; ...
%     {'2-methyl-2-butanol'}; ...
%    {'pyrrolidine'}; ...
%    {'isoborneol'}; ...
%     {'(-)-alpha-thujione'}; ...
%     {'2-hydroxy-anisole'}; ...
%     {'pyrazine'}; ...
%     {'camphor'}; ...
%     {'1,2-propanediol'}; ...
%     {'acetic acid'}; ...
%     {'2-ethylphenol'}; ...
%     {'2-propanol'}; ...
%     {'7-methylindole'}; ...
%     {'1-m-2-p'}; ...
%     {'acetylacetone'}; ...
%     {'2-butanol'}; ...
%     {'methyl acetate'}; ...
%     {'4-h-4-m-2-p'}; ...
%     {'2,3-butanediol'}; ...
%     {'2,3-butanedione'}; ...
  	{'0.069uM methyl salicylate'}; ...
     {'9.2uM 1-pentanol'}; ...
     {'6.4uM 2,5-dimethylpyrazine'}; ...
     {'2.6uM 4-hexen-3-one'}; ...
     {'1.38uM 2-nonanone'}; ...
     {'0.049uM 2-heptanone'}; ...
     {'1.8uM geranyl acetate'}; ...
     {'2.6uM 2-acetylpyridine'}; ...
     {'84uM 2-phenylethanol'}; ...
     {'8.4uM 4,5-dimethylthiazole'}; ...
     {'19uM 4-phenyl-2-butanol'}; ...
     {'4.8uM 2-methoxyphenyl acetate'}; ...
     {'33uM menthol'}; ...
     {'9.2uM ethyl acetate'};...
     {'110uM menthol'};...
%     {'1,3-propanedithiol'}; ...
%     {'3-p-2-p'}; ...
%     {'trans-3-hexenoic acid'}; ...
%     {'2-heptanol'}; ...
%     {'thiodiacetic acid'}; ...
%     {'beta-citronellol'}; ...
%     {'4-methylvaleric acid'}; ...
%     {'3-(4-hydroxyphenyl)propionic acid'}; ...
%     {'p-coumaric acid'}; ...
%     {'3-octanol'}; ...
%     {'cis-3-hexenyl acetate'}; ...
%     {'caffeic acid'}; ...
%     {'ethanol'}; ...
%     {'propyl acetate'}; ...
%     {'L-tyrosine'}; ...
%     {'citral'}; ...
%     {'cis-3-hexen-1-ol'}; ...
%     {'1,2-hexanediol'}; ...
%     {'ethyl butyrate'}; ...
%     {'dimethyl succinate'}; ...
%     {'2-ethyl-1-hexanol'}; ...
%     {'p- anisaldehyde'}; ...
%     {'benzyl acetate'}; ...
%     {'2,5-dimethylpyrazaine'}; ...
%     {'4-Hexen-3-one'}; ...
%     {'4,5-Dimethylthiazole'}; ...
%     {'1-pentanol'}; ...
%     {'1-pentanol;4-Hexen-3-one'}; ...
%     {'butyl butyrate'}; ... 
%     {'2-isobutylthiazole'}; ... 
%     {'2-methylpyrazine'}; ... 
%     {'ethyl heptanoate'}; ... 
%     {'3-pentanol'}; ...
%     {'trans-3-hexen-1-ol'}; ...
%     {'6-methyl-5-hepten-2-ol' }; ...
%     {'3-octanol'}; ...                  
%     {'methyl phenyl sulfide'}; ...      %phenyl group
%     {'anisole'}; ...
    {'2-acetylpyridine'}; ...
%     {'2,5-dimethylpyrazine'}; ...   
%     {'pentyl acetate'}; ...             %acetate
%     {'geranyl acetate'}; ...
%     {'2-methoxyphenyl acetate'}; ...
%     {'trans-2-hexen-1-al'}; ...         %aldehyde
%     {'trans,trans-2,4-nonadienal'}; ...
%     {'4-methyl-5-vinylthiazole'}; ...   %thiazole
    {'2-nonanone'}; ...                 
%     {'acetal'}; ...                     %acetal
%     {'2-phenylethanol'}; ...            %alcohol and aromatic
%     {'4-methylcyclohexane'}; ...
%     {'isoamyl acetate'};...
%     {'ethyl hexanote'}; ...             %ethyl hexanote
%     {'linalool'};...                    %strawberry odors
%     {'methyl hexanoate'};...
%     {'2-butoxy ethanol'};...
%     {'hexyl acetate'};...
    {'methyl salicylate'};...
%     {'benzyl acetate'};...
%     {'butyl acetate'};...
%     {'ethyl butyrate'};...
%     {'isopropyl butyrate'};...
%     {'isopentyl acetate'};...
%     {'methyl isovalerate'};...
%     {'methyl butyrate'};... 
%     {'limonene'};... 
%     {'geraniol'};... 
    {'2-heptanone'}; ...                   %aromatic
%     {'fluorescein'}; ...
%     {'L-glutamic acid'}; ...
%         {'L-argenine'}; ...
%         {'fructose'}; ...    
%         {'citric acid'}; ...
%         {'caffeine'}; ...             %gustatory tastants
%         {'NaCL'}; ... 
%         {'denatonium benzoate'}; ...                    
%         {'KCL'}; ...             
%         {'sucrose'}; ... 
%         {'arabinose'}; ... 
%         {'diacetyl'};...
%         {'benzaldehyde'};...
%         {'isoamyl alcohol'};...
%         {'ethyl acetate'};...
%         {'diacetyl'};...
%         {'NMM'};...
%         {'ethyl acetate & 200mM fructose'};...
%         {'1-pentanol & 3-pentanol'};...
%         {'1mM NMM & 1-pentanol'};...
%         {'4,5-dimethylthiazole & 2-phenyl ethanol'};...
%         {'3-pentanol & 2-phenyl ethanol'};...
%         {'acetal & 3-pentanol'};...
%         {'acetal & 1-pentanol'};...
%         {'1-pentanol & 4,5-dimethylthiazole'};...
%         {'acetal & 4,5-dimethylthiazole'};...
%         {'acetal & 3-pentanol'};...
%         {'acetal & 2-phenyl ethanol'};...
%         {'4,5-dimethylthiazole & 3-pentanol'};...
%         {'1-pentanol & 2-phenyl ethanol'};...
%         {'3-pentanol & 4-hexen-3-one'};...
%         {'anisole & 4-hexen-3-one'};...
%         {'NaHCO3'};...
%         {'ScramMaleP'};...
%         {'MaleP'};...
%         {'1-octanol'};...
%         {'4-methyl-5-vinylthiazole & 3-octanol'};...
%         {'4-methyl-5-vinylthiazole & methyl phenyl sulphide & pentyl acetate'};...
%         {'4-methyl-5-vinylthiazole & pentyl acetate'};...
%         {'pentyl acetate & methyl phenyl sulfide'};...
%         {'pentyl acetate & methyl phenyl sulfide & 3-octanol'};...
%         {'pentyl acetate & 4-methyl-5-vinylthiazole & 3-octanol'};...
%         {'4-methyl-5-vinylthiazole & 3-octanol'};...
%         {'pentyl acetate & 3-octanol'};...
%         {'4-methyl-5-vinylthiazole & 3-octanol & methyl phenyl sulfide'};...
%         {'pentyl acetate & 4-methyl-5-vinylthiazole & 3-octanol & methyl phenyl sulfide'};...
%         {'6-methyl-5-hepten-2-ol & 3-pentanol'};...
%         {'6-methyl-5-hepten-2-ol & 4-methyl-5-vinylthiazole'};...
%         {'6-methyl-5-hepten-2-ol & methyl phenyl sulphide'};...
%         {'3-pentanol & methyl phenyl sulphide'};...
%         {'3-pentanol & 4-methyl-5-vinylthiazole'};...
%         {'6-methyl-5-hepten-2-ol & 3-pentanol & 4-methyl-5-vinylthiazole'};...
%         {'6-methyl-5-hepten-2-ol & 3-pentanol & methyl phenyl sulphide'};...
%         {'6-methyl-5-hepten-2-ol & 3-pentanol & 4-methyl-5-vinylthiazole & methyl phenyl sulphide'};...
         {'9.2uM 1-pentanol & 2.6uM 4-hexen-3-one'};...
         {'9.2uM 1-pentanol & 28uM 4,5-dimethylthiazole'}; ...
         {'2.6uM 4-hexen-3-one & 28uM 4,5-dimethylthiazole'}; ...
%         {'1-nonanol'};...
%         {'1-hexanol'};...
%         {'1-heptanol'};...
%         {'2,3-pentanedione'};...
%         {'2-butanone'};...
%         {'Ascr2'};...
%         {'4-pheny-2-butanol'};...
%         {'myrtenal'};...
%         {'valeric acid'};...
%         {'nonane'};...
%         {'menthol'};...
%         {'Ascr3Ascr8'}; ...
%         {'Grape juice'};...
%         {'Molasses food'};...
%         {'holidic diet'};...
%         {'yeast paste'};...
%         {'Apple juice'};...
%         {'orange juice'};...
%         {'cola'};...
%         {'tea'};...
%         {'coffee'};...
%         {'milk'};...  
         {'0.01mM heptaldehyde'};...
         {'0.01mM 1-hexanol'};... 
         {'0.01mM cis-2-penten-1-ol'};...
         {'0.01mM trans-3-hexene'};...
         {'0.01mM 2-hexanone'};...
         {'0.01mM n-hexane'};...
         {'0.01mM trans-2-hexen-1-ol'};...
         {'0.01mM cis-2-hexen-1-ol'};...
         {'0.01mM 3-(Mehtylthio)-1-propanol'};...
         {'0.01mM 1-pentanol'};...
         %%%%% LWH 20210710 %%%%%% 
         {'1-11uM menthol & 1.8uM geranyl acetate'};...
         {'2-11uM menthol & 2.6uM 2-acetylpyridine'};...
         {'3-1.8uM geranyl acetate & 2.6uM 2-acetylpyridine'};...
         {'4-11uM menthol & 1.8uM geranyl acetate & 2.6uM 2-acetylpyridine'};...
         {'1mM 2-heptanone'};...
         {'1mM geranyl acetate'};...
         {'1mM menthol'};...
         {'1mM 4,5-dimethylthiazole'};...
         {'50mM propionic acid'};...
         {'10mM propionic acid'};...
         {'10mM methyl eugenol'};...
         {'9.2uM 1-pentanol'};...
         {'2.6uM 4-hexen-3-one'};...
         {'1mM methyl eugenol'};...
         {'8.4uM 4,5-dimethylthiazole'};...
         {'9.2uM 1-pentanol & 8.4uM 4,5-dimethylthiazole'};...
         {'2.6uM 4-hexen-3-one & 8.4uM 4,5-dimethylthiazole'};...
         {'0.049uM 2-heptanone & 9.2uM 1-pentanol'};...
         {'0.049uM 2-heptanone & 2.6uM 4-hexen-3-one'};...
     
        %%%%% CSH 20220620 %%%%%
        {'5mixed: 9.2uM 1-pentanol & 8.4uM 4,5-dimethylthiazole & 0.049uM 2-heptanone & 0.069uM methyl salicylate & 9.2uM ethyl acetate'}];
     

                             
%% %concentration list
odor_concentration_list = [ {'1mM'}; {'0.1mM'}; {'0.01mM'}; ...
    {'10^-8'}; {'10^-7'}; {'10^-6'}; {'10^-5'}; {'10^-4'};{'10^-3'}; ...
%     {'10^-3'};{'10^-2'}; {'10^-1'}; ...
    {'1'}    
%     {'3x10^-11'};{'3x10^-10'};{'3x10^-9'}; {'3x10^-8'}; {'3x10^-7'} ; {'3x10^-6'}; {'3x10^-5'}; {'3x10^-4'} ;...
%     {'200uM'};{'500uM'}; {'0.1mM'}; {'1mM'}; {'2mM'}; {'5mM'}; {'10mM'}; {'20mM'};  {'50mM'}; {'100mM'}; {'200mM'};  {'500mM'}; {'1M'}; {'2M'};...
%     {'3x10^-6;10^-7'}; {'3x10^-6;10^-6'}; {'3x10^-6;10^-5'};{'3x10^-6;10^-4'}; ...
%     {'10^-5;10^-7'}; {'10^-5;10^-6'}; {'10^-5;10^-5'};{'10^-5s;10^-4'}; ...
%     {'10^-7;10^-6'};{'10^-6;10^-6'};{'10^-5;10^-6'};{'10^-6;10^-5'};{'10^-5;10^-5'};{'10^-5;5x10^-6'};{'10^-5;10^-7'};{'10^-5;3x10^-7'};...
%     {'10^-5;3x10^-6'};{'10^-4;10^-6'};{'10^-6;10^-4'};{'10^-4.3'};{'10^-4.7'};...
%     {'2x10^-5'};{'5x10^-5'};{'2x10^-6'};{'5x10^-6'};{'2x10^-7'};{'5x10^-7'};{'7.5x10^-5'};{'2.5x10^-5'}; ...
%     {'10^-6;10^-6;10^-6'}; {'10^-6;10^-6;10^-6;10^-6'}; {'5x10^-7;10^-6;10^-6'};  {'5x10^-7;10^-6'};{'5x10^-7;10^-6;10^-6;10^-6'};...
%     {'1x'};{'.9x'};{'.8x'};{'.7x'};{'.5x'};{'.3x'};{'.2x'};{'.1x'};{'.05x'}...
    ];    %concentrations
    
%odor_concentration_list = [{'10^-8'}; {'10^-7'}; {'10^-6'}; {'10^-5'}; {'10^-4'}; {'1 mM'}; {'2 mM'}; {'5 mM'};  {'6 mM'}; {'10 mM'}; {'20 mM'}; {'50 mM'}; {'100 mM'}; {'200 mM'};  {'500 mM'}; {'1 M'}; {'2 M'}];    %concentrations

%% %colormap
odor_num = length(odor_list);
con_num = length(odor_concentration_list);

color_num = odor_num*con_num;
if color_num<128
    color_num = 128;
elseif color_num<256
    color_num = 256;
elseif color_num<512
    color_num = 512;
end

odor_colormap = colorcube(color_num); 
odor_colormap = odor_colormap(1:odor_num*con_num,:); 

%% %show colormap
data_show = 1:odor_num*con_num;
data_show = reshape(data_show,con_num, odor_num)';

figure
imagesc(data_show); 
colormap(odor_colormap);

title('Odor Colormap')
set(gca,'XTick',1:con_num);
set(gca,'XTickLabel',odor_concentration_list)
xlabel('Concentration');
set(gca,'YTick',1:odor_num);
set(gca,'YTickLabel',odor_list);
ylabel('Odor Type');

%% Save data and figure
currentFolder = pwd;
path = [currentFolder, '\data\'];
if ~exist(path, 'dir')
    mkdir(path);
end
save([path, 'odor_inf'], 'odor_list', 'odor_concentration_list', 'odor_colormap');
saveas(gcf,[path, 'odor_colormap.fig']);